# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="battle-towers" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="0.9.0" #mandatory
 # A display name for the mod
displayName="Passer's Battle Towers" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/Asterxis/battle-towers" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional
# A text field displayed in the mod UI
credits="Draylar for letting me use their source code as a reference." #optional
# A text field displayed in the mod UI
authors="Passer/Asterxis" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Battle Towers, reborn for 1.15.2 Forge!
Not 100% finished yet, may be a tad bit buggy. Please report any you find on the curseforge page please!'''
